### ISSUE TITLE
Upload Blogs And Comment As An Author

### ISSUE THREAD

**Issue by Indk0** [Indk0/FinMeBlog#4]
As an author, I can access my account when logged in so that I can upload blogs and comments so that I can track my activity.

- [x] A dedicated page on the nav bar should have the account button where the author can track its activity.
- [x] The author should be able to edit and delete blogs and comments, including images.
- [ ] A signup and a delete account option should be available to the user.
